name: CI/CD Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"
          - "windows-latest"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      # Install project dependencies
      - name: Install Composer Dependencies
        run: composer install

      # Run PHPUnit tests
      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
        
